version: '3.7'
services:
 mondodb_container:
  image: mongo:latest 
  environment:
    MONDO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
  ports:
    - 27017:27017
  volumes: 
    - mongodb_data_container:/data/db
volumes:
 mondodb_data_container:
